Feature/full graph from parser
Hexa6IF/pld_agile pull request #7
Opened 2019-11-27 19:13 UTC by Arteox

2019-11-27 21:36 UTC, slokuge requested changes
Quelques petits trucs à règler

2019-11-27 21:36 UTC, slokuge commented on src/main/deliferoo/model/AbstractEdge.java
> +	this.nodeDest = new Node(nodeDest);
Pourquoi créer des nouvelles noeuds ici ?

2019-11-27 21:36 UTC, slokuge commented on src/main/deliferoo/model/AbstractEdge.java
> +	this.nodeDest = new Node(nodeDest);
Même question

2019-11-27 21:36 UTC, slokuge commented on src/main/deliferoo/xml/XMLParser.java
> +    private Integer count2 = 0;
Ce serait bien d'avoir des noms plus explicits que `count1` `count2`

2019-11-27 23:09 UTC, Arteox commented on src/main/deliferoo/model/AbstractEdge.java
> +	this.nodeDest = new Node(nodeDest);
Je vérifie si ça marche sans tout à l'heure j'avais eu des bugs et je crois que c'était peut-être à cause d'un problème de passage par référence au lieu de passage par valeur (pointer null sinon)

2019-11-28 00:00 UTC, slokuge approved these changes
Okay

2019-11-28 00:00 UTC, merged